# Generated by Django 5.0.2 on 2024-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FST', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('NPV', models.DecimalField(decimal_places=0, max_digits=12)),
                ('IRR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PI', models.DecimalField(decimal_places=2, max_digits=5)),
                ('SE', models.DecimalField(decimal_places=0, max_digits=12)),
                ('BP', models.DecimalField(decimal_places=0, max_digits=12)),
                ('RESERVES', models.DecimalField(decimal_places=0, max_digits=12)),
                ('PROD_RATE', models.DecimalField(decimal_places=0, max_digits=12)),
                ('ORE_TYPE', models.CharField(max_length=250)),
                ('STORE_FILE', models.FileField(upload_to='XLSFILES')),
            ],
        ),
    ]
